trigger: [master]
pr: [master]

jobs:
- job: MatricesGenerator
  pool:
    name: kidev-pool
    demands:
    - Agent.OS -equals Windows_NT
  steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.13.0'
        addToPath: true
    - bash: python ci/generate_azure_pipelines_matrices.py
      name: mtrx
      displayName: Generate test matrices and set variables in Azure Pipelines

- job: Windows
  dependsOn: MatricesGenerator
  pool:
    name: kidev-pool
    demands:
    - Agent.OS -equals Windows_NT
  strategy:
    matrix: $[ dependencies.MatricesGenerator.outputs['mtrx.windows'] ]
  variables:
    MODULES_FOLDER: '$(System.DefaultWorkingDirectory)\CachedPowershellModules'
    startYear: $[format('{0:yyyy}', pipeline.startTime)]
    startMonth: $[format('{0:MM}', pipeline.startTime)]
  steps:
    - template: ci/steps.yml
