name: Test install-qt-action

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build-and-deploy:
    name: "Test install-qt-action"
    env:
      workspace_root: '/home/runner/work/aqtinstall/aqtinstall'
      qt_host: 'windows'
      qt_target: 'desktop'
      qt_version: '6.8.0'
      qt_host_arch: 'win64_msvc2022_64'
      qt_host_arch_folder: 'msvc2022_64'
      qt_target_wasm: 'wasm_singlethread'
      qt_modules: 'qtquick3d qtpdf'
      qt_modules_wasm: 'qtquick3d'
      qt_root: '/home/runner/work/aqtinstall/aqtinstall/Qt'
    runs-on: ubuntu-24.04
    steps:
      - name: Install tools
        shell: bash
        run: |
          sudo apt update
          sudo apt-get -y install build-essential libgl1-mesa-dev curl python3 python3-venv

      - name: Install Qt for host architecture
        uses: jurplel/install-qt-action@v4.1.1
        with:
          version: ${{ env.qt_version }}
          host: ${{ env.qt_host }}
          target: ${{ env.qt_target }}
          arch: ${{ env.qt_host_arch }}
          dir: ${{ env.workspace_root }}
          modules: ${{ env.qt_modules }}
          cache: 'true'
          cache-key-prefix: 'install-qt-host'
          aqtsource: 'git+https://github.com/Kidev/aqtinstall.git@semver2'

      - name: Install Qt for target architecture
        uses: jurplel/install-qt-action@v4.1.1
        with:
          version: ${{ env.qt_version }}
          host: ${{ env.qt_host }}
          target: ${{ env.qt_target }}
          arch: ${{ env.qt_target_wasm }}
          dir: ${{ env.workspace_root }}
          modules: ${{ env.qt_modules_wasm }}
          cache: 'true'
          cache-key-prefix: 'install-qt-wasm'
          aqtsource: 'git+https://github.com/Kidev/aqtinstall.git@semver2'

      - name: Checking installs
        shell: bash
        run: |
          ls "${{ env.qt_root }}/${{ env.qt_version }}/${{ env.qt_host_arch_folder }}/lib/"
          ls "${{ env.qt_root }}/${{ env.qt_version }}/${{ env.qt_target_wasm }}/lib/"
          
          files=(
            "${{ env.qt_root }}/${{ env.qt_version }}/${{ env.qt_host_arch_folder }}/lib/Qt6Quick3D.lib"
            "${{ env.qt_root }}/${{ env.qt_version }}/${{ env.qt_host_arch_folder }}/lib/Qt6Pdf.lib"
            "${{ env.qt_root }}/${{ env.qt_version }}/${{ env.qt_target_wasm }}/lib/Qt6Quick3D.lib"
          )

          for file in "${files[@]}"; do
            if [ ! -f "$file" ]; then
              echo "Error: File not found: $file"
              exit 1
            fi
          done

          echo "All required files are present."
